### ISSUE TITLE
surfdist version on pip is out of date

### ISSUE THREAD

**Issue by dmoracze** [NeuroanatomyAndConnectivity/surfdist#11]
0.13.18 is the most recent version on pip and is incompatible with python 3

**Comment by margulies** [comment]
Thank you for catching this issue. I've finally gotten around to updating the pip package (current version is 0.15.4). Could you let me know if you encounter any installation issues? It should now be compatible with python >=3.6

**Comment by dmoracze** [comment]
Hello - thank you for updating this. The installation worked fine.
I went on and solved my task by going directly to gdist, but if I have some time in the near future I'll try to compute the distance matrix using surfdist as well.
